route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#random'
            api_url: 'https://hooks.slack.com/services/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'