version: "3.9"
services:


  grafana-hook:
    container_name: grafana-hook
    image: grafana-hook
    build: .
    ports:
      - '9000:9000'
    environment:
      TOKEN: 'some_myteam_bot_token'
      API_URL: 'https://api.internal.myteam.mail.ru'
      API_PREFIX: /bot/v1
      GRAFANA_URL: http://localhost:3000
      GF_LOGIN: user
      GF_PASSWORD: 1235
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:7.3.6
    restart: unless-stopped
    ports:
      - 80:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,blackmirror1-singlestat-math-panel
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=1235
    networks:
      - monitoring
    volumes: 
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - graphite
  
  statsd:
    build: ./statsd
    container_name: myop-statsd
    environment: 
      - GRAPHITE_PORT_2003_TCP_ADDR=graphite
    ports:
      - "8125:8125/udp"
      - "8126:8126"
    networks:
      - monitoring

  graphite:
    build: ./graphite
    image: myoperator/graphite_statsd
    container_name: myop-graphite-carbon
    ports:
      - "8080:80"
    environment: 
      - GRAPHITE_STATSD_HOST=statsd
    expose: 
      - 8080
      - "2003-2004"
      - "2023-2024"
    volumes:
      - graphite_data:/opt/graphite/storage
      - ./log/graphite:/var/log/graphite
    depends_on:
      - statsd
    networks:
      - monitoring

volumes:
    grafana_data: {}
    graphite_data: {}

networks:
  monitoring:
    name: monitoring
    driver: bridge