---
openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  "/grafana/events/{chatId}":
    post:
      summary: Grafana Events
      description: Метод для получения webhook от Grafana без указания bot_token в
        path
      operationId: grafana_events_grafana_events__chatId__post
      parameters:
      - description: ID чата в ICQ/Myteam, куда должно быть отправленно сообщение
        required: true
        schema:
          title: ID чата
          type: string
          description: ID чата в ICQ/Myteam, куда должно быть отправленно сообщение
        name: chatId
        in: path
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Event"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/grafana/events/{token}/{chatId}":
    post:
      summary: Grafana Events
      description: Метод для получения webhook от Grafana с указанием bot_token в
        path
      operationId: grafana_events_grafana_events__token___chatId__post
      parameters:
      - required: true
        schema:
          title: Токен от бота
          type: string
        name: token
        in: path
      - description: ID чата в ICQ/Myteam, куда должно быть отправленно сообщение
        required: true
        schema:
          title: ID чата
          type: string
          description: ID чата в ICQ/Myteam, куда должно быть отправленно сообщение
        name: chatId
        in: path
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Event"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    Event:
      title: Event
      required:
      - title
      - ruleId
      - ruleName
      - state
      - evalMatches
      - orgId
      - dashboardId
      - panelId
      - tags
      - ruleUrl
      type: object
      properties:
        title:
          title: Title
          type: string
        ruleId:
          title: Ruleid
          type: integer
        ruleName:
          title: Rulename
          type: string
        state:
          "$ref": "#/components/schemas/State"
        evalMatches:
          title: Evalmatches
          type: array
          items:
            "$ref": "#/components/schemas/evalMatch"
        orgId:
          title: Orgid
          type: integer
        dashboardId:
          title: Dashboardid
          type: integer
        panelId:
          title: Panelid
          type: integer
        tags:
          title: Tags
          anyOf:
          - type: object
          - type: object
        ruleUrl:
          title: Ruleurl
          type: string
        imageUrl:
          title: Imageurl
          type: string
        message:
          title: Message
          type: string
      description: Модель для эвента от Grafana
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            "$ref": "#/components/schemas/ValidationError"
    State:
      title: State
      enum:
      - ok
      - paused
      - alerting
      - pending
      - no data
      type: string
      description: Enum статусов Alert от Grafana
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    evalMatch:
      title: evalMatch
      required:
      - value
      - metric
      type: object
      properties:
        value:
          title: Value
          anyOf:
          - type: string
          - type: integer
        metric:
          title: Metric
          type: string
        tags:
          title: Tags
          anyOf:
          - type: string
          - type: object
      description: Модель для значений метрик в эвенте от Grafana

